- name: Execute script on localhost
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Run script
      script:
        src: /home/paulyflu/Escritorio/VM_deployment.sh
      become: yes
      args:
        executable: /bin/bash
