- name: Execute script on localhost
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Run script
      script:
        src: /home/paulyflu/Escritorio/VM_deployment.sh
        remote_src: true
