---
- name: Create VirtualBox VM
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Define variables
      set_fact:
        vm_name: "test_vm1"
        vm_os_type: "Ubuntu_64"
        vm_ram: "1024"
        vm_vram: "16"
        vm_hdd_name: "test_vm1.vdi"
        vm_hdd_size: "20480"
        vm_hdd_controller: "SATA"
        vm_network_adapter: "bridged"
        vm_network_bridge: "wlo1"
        iso_path: "/home/paulyflu/ubuntu-21.10-desktop-amd64.iso"
        vm_dvd_image_url: "http://releases.ubuntu.com/21.10/ubuntu-21.10-desktop-amd64.iso"
        vm_dvd_controller: "IDE"
        vm_dvd_boot_order: "1"

    - name: Create VM
      become_user: "{{ ansible_user }}"
      command:
        cmd: VBoxManage createvm --name "{{ vm_name }}" --ostype "{{ vm_os_type }}" --register
      register: createvm_result
      changed_when: "'VM with name {{ vm_name }} already exists' not in createvm_result.stdout"

    - name: Configure VM
      become_user: "{{ ansible_user }}"
      block:
        - name: Create VM HDD
          command:
            cmd: VBoxManage createhd --filename "{{ vm_hdd_name }}" --size "{{ vm_hdd_size }}" --format VDI --variant Standard
          args:
            creates: "{{ vm_hdd_name }}"

        - name: Attach VM HDD
          command:
            cmd: VBoxManage storageattach "{{ vm_name }}" --storagectl "{{ vm_hdd_controller }}" --port 0 --device 0 --type hdd --medium "{{ vm_hdd_name }}"

        - name: Attach VM DVD
          command:
            cmd: VBoxManage storageattach "{{ vm_name }}" --storagectl "{{ vm_dvd_controller }}" --port 0 --device 0 --type dvddrive --medium "{{ iso_path }}"

        - name: Modify VM settings
          command:
            cmd: VBoxManage modifyvm "{{ vm_name }}" --memory "{{ vm_ram }}" --vram "{{ vm_vram }}" --nic1 "{{ vm_network_adapter }}" --bridgeadapter1 "{{ vm_network_bridge }}" --boot1 dvd --boot2 disk --boot3 none --boot4 none
      changed_when: "'already exists' not in createvm_result.stdout"

    - name: Print VM created successfully
      debug:
        msg: "VM created successfully."

